import { GoogleGenAI } from "@google/genai";

const IMAGE_MODEL = 'imagen-4.0-generate-001';
type AspectRatio = '1:1' | '16:9' | '9:16' | '4:3' | '3:4';

/**
 * Generates an image based on a user prompt using the Imagen model.
 * @param prompt The user's text prompt describing the image.
 * @param aspectRatio The desired aspect ratio for the image.
 * @returns A data URL string of the generated JPEG image.
 */
export const generateImage = async (prompt: string, aspectRatio: AspectRatio = '1:1'): Promise<string> => {
    try {
        // FIX: Instantiate the client here to use the latest API key.
        const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
        
        const response = await ai.models.generateImages({
            model: IMAGE_MODEL,
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: aspectRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        }
        
        throw new Error("No image was generated by the API.");

    } catch (error) {
        console.error("Error generating image with Imagen:", error);
        throw new Error("Failed to generate image using the Imagen API.");
    }
};